name: ukk
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter
  url_launcher: ^6.2.2
  
flutter: 
  uses-material-design: true

